matrix:
  matrix:
  - TEST=make-amd64
language: c
dist: focal
addons:
  apt:
    packages:
    - automake
    - libtool
    - autotools-dev
    - libseccomp-dev
    - git
    - make
    - libcap-dev
    - cmake
    - pkg-config
    - gcc
    - wget
    - go-md2man
    - libsystemd-dev
    - gperf
    - clang-format
  sonarcloud:
    organization: "l2dy-sonarcloud"
    token:
      secure: "Y/9J8parLqw6ZzL55bsIuYIAl+xsCa6K6gVBfphWlLquy4rOHiJbcXf00UhQr7SbuPB0EPJEc4QoIm/eXatBC9M8lvkuFbjtLFtHxOahyLv4myN9r0h47f3PCMdXGE5lfkR0bYGBeAHFbSdg/dNALHupKH/WvLDh0WUZAG9SsytTJGDVZr9ZLNhdVn77enSNR+WkVx0JCnsoElHBYSq8/PHiei//kzEk7a7WgGahNiOCkFQHtiLVcs6aQyyEcM3Uvd/LMQri9whfUjzYytTFlmDl7OGwP7VqnRaaxfoPMTo7wGoz4tGENe3K5lHGxgwVHdSm9ytcbgYpZ0BGZdLuQtw7e32Q6oOKmbz1/9POSDACY1olCjAJyyNSlunrM+S3NQaCOdIIgE4GQxdmXjnzRjMcIo5fD5qPInHsdiW1lBBTdhWoYVbqfh2gXoyqk+WrqtDehVm0lSnug745u5rtbaNZVYeg4f0lL/qBsO5szkwlo6HBFFdStfCk4ienD0HPNmz0KXtTbq7WuqEr53245zCcRd4vkMHkbtlh2d+1jLZ+UNq+jLV6MmpadAPvzMpnvC0utCTen/bu3c5ayKwrUTLMQ5QQR1T0rGdQkBJhaLhv7zv2JTZFXYGjYGGPBy6hmdl3KTjQOeM78ODIzf0oeY9ZHMJurUfuEtOfwEzHC9c=" # encrypted value of your token

script:
  # Wraps the compilation with the Build Wrapper to generate configuration (used
  # later by the SonarScanner) into the "bw-output" folder
  - build-wrapper-linux-x86-64 --out-dir bw-output <your clean build command>
  # And finally run the SonarCloud analysis - read the "sonar-project.properties"
  # file to see the specific configuration
  - sonar-scanner -Dsonar.cfamily.build-wrapper-output=bw-output
before_install:
- git submodule update --init --recursive
- git clone --depth=1 git://github.com/lloyd/yajl
- "(cd yajl && ./configure -p /usr && make && sudo make install)"
# CRIU supports armhfp, aarch64, ppc64le, s390x and x86_64. The PPA has only packages for x86_64
- if test $TRAVIS_CPU_ARCH = amd64; then sudo add-apt-repository -y ppa:criu/ppa; sudo apt-get -q update; sudo apt-get -y install criu; fi
script:
- ./autogen.sh && ./configure CFLAGS='-Wall -Werror' && build-wrapper-linux-x86-64 --out-dir bw-output make -j $(nproc)
- sonar-scanner -Dsonar.cfamily.build-wrapper-output=bw-output -Dsonar.cfamily.threads=2 -Dsonar.cfamily.cache.enabled=false
